title: AI Reader
description: AI Reader is a free, all-in-one desktop software to help researchers and students conduct research with ease in the digital age.
theme: just-the-docs

url: https://boan-anbo.github.io/ai-reader

aux_links:
  Template Repository: https://github.com/boan-anbo/ai-reader
