title: AI Reader Documentation
description: AI Reader is a free, all-in-one desktop software to help researchers and students conduct research with ease in the digital age.
theme: just-the-docs
logo: assets/general/ai_reader_icon.png
favicon_ico: assets/general/icon.ico

url: https://boan-anbo.github.io/ai-reader

aux_links:
  Issues: https://github.com/boan-anbo/ai-reader/issues
  Github: https://github.com/boan-anbo/ai-reader

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html
